"""init

Revision ID: 5f9d308c4ba2
Revises: 
Create Date: 2021-09-28 11:17:08.693499

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5f9d308c4ba2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gameshistory',
    sa.Column('game_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('played_at', sa.DateTime(), nullable=False),
    sa.Column('telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('field_size', sa.Integer(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('game_id')
    )
    op.create_index(op.f('ix_gameshistory_telegram_id'), 'gameshistory', ['telegram_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_gameshistory_telegram_id'), table_name='gameshistory')
    op.drop_table('gameshistory')
    # ### end Alembic commands ###
